test: move test from floxpkgs

diff --git a/.github/workflows/compare-nix.yml b/.github/workflows/compare-nix.yml
--- a/.github/workflows/compare-nix.yml
+++ b/.github/workflows/compare-nix.yml
@@ -62,9 +62,10 @@ jobs:
         echo "selfURI: $selfURI" >&2;
 
         echo "Installing deps" >&2;
-        nix profile install 'nixpkgs#krb5^out,dev' -L;
-        nix profile install 'nixpkgs#pkg-config'         -L;
-        nix profile install "$selfURI#etc-profiles"      -L;
+        nix profile install 'nixpkgs#krb5^out,dev'  -L;
+        nix profile install 'nixpkgs#pkg-config'    -L;
+        nix profile install "$selfURI#etc-profiles" -L;
+        nix profile install "$selfURI#nodejs"       -L;
 
         echo "Activating env" >&2;
         export FLOX_ENV="$HOME/.nix-profile";
@@ -82,5 +83,22 @@ jobs:
           echo "---" >&2;
           pkg-config --list-all >&2;
           echo "---" >&2;
+          exit 1;
+        fi
+
+    - name: Node.js KRB5 Test
+      shell: bash
+      run: |
+        export FLOX_ENV="$HOME/.nix-profile";
+        . "$FLOX_ENV/etc/profile";
+        mkdir ./node-krb5;
+        cd ./node-krb5;
+        # Install `krb5' module with `npm'.
+        npm i krb5;
+        if [[ -x "$PWD/node_modules/krb5/build/Release/krb5.node" ]]; then
+          echo "PASS: npm" >&2;
+          exit 0;
+        else
+          echo "FAIL: npm" >&2;
           exit 1;
         fi
diff --git a/.github/workflows/trivial-test.yml b/.github/workflows/trivial-test.yml
--- a/.github/workflows/trivial-test.yml
+++ b/.github/workflows/trivial-test.yml
@@ -56,6 +56,7 @@ jobs:
         echo "Creating flox.nix" >&2;
         cat <<EOF > ./flox.nix
         {
+          packages.nixpkgs-flox.nodejs = {};
           packages.nixpkgs-flox.krb5 = {
             meta.outputsToInstall = ["out" "dev"];
           };
@@ -93,5 +94,21 @@ jobs:
           echo "---" >&2;
           runEnv pkg-config --list-all >&2;
           echo "---" >&2;
+          exit 1;
+        fi
+
+    - name: Node.js KRB5 Test
+      shell: bash
+      run: |
+        runEnv() { flox activate -e krb5-dev -- "$@"; }
+        mkdir ./node-krb5;
+        cd ./node-krb5;
+        # Install `krb5' module with `npm'.
+        runEnv npm i krb5;
+        if [[ -x "$PWD/node_modules/krb5/build/Release/krb5.node" ]]; then
+          echo "PASS: npm" >&2;
+          exit 0;
+        else
+          echo "FAIL: npm" >&2;
           exit 1;
         fi
